### ISSUE TITLE
NullPointerException with regex ((?(1)2|3))

### ISSUE THREAD

**Issue by CodesAway** [CodesAway/RegExPlus#5]
Exception in thread "main" java.lang.NullPointerException
	at info.codesaway.util.regex.Refactor.anyCondition(Refactor.java:1339)
	at info.codesaway.util.regex.Refactor.acceptTestingGroup(Refactor.java:1277)
	at info.codesaway.util.regex.Refactor.refactorConditionalPattern(Refactor.java:2611)
	at info.codesaway.util.regex.Refactor.refactor(Refactor.java:971)
	at info.codesaway.util.regex.Refactor.<init>(Refactor.java:461)
	at info.codesaway.util.regex.Refactor.<init>(Refactor.java:421)
	at info.codesaway.util.regex.Pattern.compile(Pattern.java:3313)
	at info.codesaway.util.regex.Pattern.<init>(Pattern.java:3172)
	at info.codesaway.util.regex.Pattern.compile(Pattern.java:1892)
	at info.codesaway.util.regex.Pattern.compile(Pattern.java:1862)
	at info.codesaway.util.regex.Pattern.compile(Pattern.java:1802)
	at info.codesaway.util.RegexTesting.main(RegexTesting.java:10)

**Comment by CodesAway** [comment]
Don't see a specific test for this, so will add one
